// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOP_Lab7.Data;

#nullable disable

namespace OOP_Lab7.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230518210445_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOP_Lab7.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AbroadTransfersAmount")
                        .HasColumnType("float");

                    b.Property<double>("AdditionalJobIncome")
                        .HasColumnType("float");

                    b.Property<double>("AuthorAwardsAmount")
                        .HasColumnType("float");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("int");

                    b.Property<double>("GoodsGiftsAmount")
                        .HasColumnType("float");

                    b.Property<double>("GoodsSellsIncome")
                        .HasColumnType("float");

                    b.Property<double>("MainJobIncome")
                        .HasColumnType("float");

                    b.Property<double>("MoneyGiftsAmount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("OOP_Lab7.Data.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Taxes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Tax");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OOP_Lab7.Data.AbroadTransfersTax", b =>
                {
                    b.HasBaseType("OOP_Lab7.Data.Tax");

                    b.HasDiscriminator().HasValue("AbroadTransfersTax");
                });

            modelBuilder.Entity("OOP_Lab7.Data.GiftsTax", b =>
                {
                    b.HasBaseType("OOP_Lab7.Data.Tax");

                    b.HasDiscriminator().HasValue("GiftsTax");
                });

            modelBuilder.Entity("OOP_Lab7.Data.GoodsTax", b =>
                {
                    b.HasBaseType("OOP_Lab7.Data.Tax");

                    b.HasDiscriminator().HasValue("GoodsTax");
                });

            modelBuilder.Entity("OOP_Lab7.Data.JobTax", b =>
                {
                    b.HasBaseType("OOP_Lab7.Data.Tax");

                    b.HasDiscriminator().HasValue("JobTax");
                });

            modelBuilder.Entity("OOP_Lab7.Data.MilitaryTax", b =>
                {
                    b.HasBaseType("OOP_Lab7.Data.Tax");

                    b.HasDiscriminator().HasValue("MilitaryTax");
                });

            modelBuilder.Entity("OOP_Lab7.Data.Tax", b =>
                {
                    b.HasOne("OOP_Lab7.Data.Person", "Person")
                        .WithMany("Taxes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("OOP_Lab7.Data.Person", b =>
                {
                    b.Navigation("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
